// Code generated by tygo. DO NOT EDIT.

//////////
// source: Author.go

export interface Author extends User {
  biography: string;
  publisher: string;
}

//////////
// source: User.go

export interface User {
  email: string;
  name: string;
  gender: number /* int */;
  age: number /* int */;
  birthday: string;
  country: string;
  province: string;
  city: string;
  detail_address: string;
}
